services:
  # Redis for job queue
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  app:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - redis
    volumes:
      - ./temp:/app/temp
      - ./models:/app/models
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    restart: unless-stopped

volumes:
  redis_data: